# Import all models here so that Base has them registered for Alembic migrations.
from voice_api.db.base_class import Base  # noqa: F401
from voice_api.models import (  # noqa: F401
    Agent,
    AgentVersion,
    AgentVersionKnowledge,
    AgentVersionTool,
    BrowserSession,
    Call,
    Callback,
    Classification,
    Contact,
    ContactFact,
    ContextSummary,
    ConversationMessage,
    Exchange,
    FlowNodeVisit,
    InboundWebhookMessage,
    IntegrationConnection,
    IntegrationMedia,
    IntegrationSecret,
    KnowledgeBase,
    KnowledgeChunk,
    KnowledgeSource,
    Run,
    RunArtifact,
    RuntimeEndpoint,
    Tool,
    ToolInvocation,
    ToolInvocationResult,
    ToolVersion,
    TraceSpan,
    WorkspaceSettings,
)
