# Import all models here so that Base has them registered for Alembic migrations.
from voice_api.db.base_class import Base  # noqa: F401
from voice_api.models import (  # noqa: F401
    Agent,
    AgentVersion,
    AgentVersionTool,
    AnalysisEvaluation,
    AnalysisRule,
    AnalysisRun,
    Call,
    Callback,
    Contact,
    ConversationMessage,
    ConversationSummary,
    EvidenceBatch,
    EvidenceEvent,
    Exchange,
    IntegrationConnection,
    KnowledgeBase,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeSource,
    Run,
    RunArtifact,
    RuntimeEndpoint,
    SafetyIncident,
    SafetyPattern,
    Tool,
    ToolInvocation,
    ToolVersion,
    TraceSpan,
    WorkspaceSettings,
)
